version: "3.9"
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html/
  php:
    image: php:8.3-fpm
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html/
